### PR TITLE
Add DNS send file to powershell client, other bug fixes

### PR DESCRIPTION
**Pull request by khr0x40sh**
ADDS:
- Added Send-DNSPacket to send questions for both DNSTXT and DNSResolved in the powershell client
- Added the ability to send files over both DNS modes in powershell client
- Added support for stacked DNS TXT requests in the python DNS TXT server
- Added the ability to stack (optional switch) up to 7 DNS questions for DNSTXT powershell client (this decreases the send time for large files 50% or more)
- Increased maximum file size to send from 3.4MB to ~75GB (maximum packets to send from 99,999 to 2,147,483,647) using a 4 byte header (file_status) instead of a string of the int for DNSTXT server/clients
- Added the ability to change SMTP To, From and Subject
- Added the ability to change server SMB port
- Added a Mozilla User Agent for python HTTP client
- Fixed Bug in SFTP powershell client where filetransfer was not being called

ISSUES:
- Removed DNS response check in dns_client as the response was not sent from the server often enough it was a problem. 
- DNS TXT server does not seem to always send the response or an ICMP error is sent causing issues with the clients.  This may be due to no actual service is bound to UDP 53. A solution we are looking into is using python DNSlib instead of scapy to send and receive DNS requests.
- The Renci.SSH.NET DLL that is embedded is compiled for .NET Target 4.0, not 3.5, therefore the SFTP powershell client errors and fails on Windows 7.  This DLL also triggers McAfee AV as a PS/Dropper.
- A potential memory leak has been identified when using the DNS_resolved server.  Investigation into what or why is still pending.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
This is awesome, thank you for the significant pull request and the amount of work you put into this (both developing and documenting what you've done). To confirm, are the "Issues" items that are still left to be resolved?

I'm open to using dnslib (I need to look into it) as a replacement for scapy for DNS transfers. Scapy was largely chosen because it was "easy enough" to manipulate packets as they are received, and for responses, but if dnslib is easier and/or more reliable, I'm interested in it. But I am guessing this isn't done yet (I'm about to review code, but am basing this statement off of your documented modifications above)?

I believe @rvrsh3ll had helped with the SFTP specifically within PowerShell (really he did the whole PowerShell client). Is this something you could easily change/modify @rvrsh3ll to use 3.5, or was it written in 4.0?

Finally, do you have any reproducible steps for the memory leak? Also, I assume this may not matter if the script changes to dnslib rather than sticking with Scapy.

**Comment by khr0x40sh** [comment]
Yeah, either outstanding or ones we've introduced with our updates.

I've used dnslib in a previous project, and I think our fork is probably going to go that direction.  I agree with you about Scapy is a great tool for packet manipulation, but it seems without an actual bound server, some unexpected (or maybe expected) results happen.  The temporary workaround was to use Responder just have something there. @butlerallenj can weigh in on the expected effort to implement DNSLib further as his python kung-fu is a bit stronger than mine, but I really don't see it being a bridge too far.

As far as the SFTP lib, it should just take a recompile at the target .NET (3.5) and have powershell base64 encode it.  Because McAfee and a few AV vendors flag just the DLL as a malicious PS/Dropper, I may add the check for the .NET version and side load the DLL somehow in my fork.  One thing to be aware of is that some versions of Win 10/Server 2k12/16 may not always have .NET 3.5 on them either (a very rare case, but I've seen it before).

The only thing I can report on the memory leak is that if you run top and watch the Egress-Assess server in dns_resolved mode it continues to creep up over a large transfer.  Again this is something we just noticed and we think it may be something with Scapy?  We didn't observe this behavior with any of the other modules during our testing.

I'm happy to pitch in as needed and I have time, just let me know if there is anything I can help with.

**Comment by rvrsh3ll** [comment]
So for the sftp dll. That was a direct b64 of renci. At the time 3.5 was the latest and like you say now it's not on win10 by default so it's an operational decision which to use 3.5 or >4. I think adding both to it and doing a check is the right way to go.

**Comment by ChrisTruncer** [comment]
This is solid stuff, thanks for the additional contributions!

**Comment by ChrisTruncer** [comment]
Have you tested sending data directly to this with DNS (setting --server dns and then pointing the client dns at the server's IP)? I've tested locally and I just spun up a server online, however I'm not getting any of the DNS packets that are being sent from the server to be decoded or saved to disk.

**Comment by khr0x40sh** [comment]
I always saw packets in the tests I ran, but maybe something I or @butlerallenj did accidentally broke it.  I think we saw an issue while updating to DNSlib on my fork and corrected it there, but I will poke around and see if I identify what's going on.

I assume this is the python client to server?

**Comment by butlerallenj** [comment]
@khr0x40sh @ChrisTruncer We actually ran into this issue ourselves as well with the python client even before we began working on our changes. It seems that Scapy does not respond with UDP packets but rather ICMP or something. We were able to resolve this by binding something to UDP 53 (we used Responder). I actually have a modifed version that binds to TCP/UDP 53 using SocketServer to fix this issue. This shouldn't happen when using the DNSLib version `--server dns_complete`

**Comment by ChrisTruncer** [comment]
ok, that was likely the issue. I didn't realize that server-side it was changed to dns_correct. I think it would be worthwhile to just replace the existing dns module with the dnslib one and keep the name "dns" just for ease of use.

**Comment by butlerallenj** [comment]
I agree. The only reason I did not do this was because it was a complete rewrite. I figured I'd leave that decision up to you

**Comment by ChrisTruncer** [comment]
I just ran another test, and this is looking good overall on my end, and I think could be merged in.

@rvrsh3ll is there anything else you want to test or review before merging?

**Comment by ruddawg26** [comment]
FYI, we did catch the other day that the DNS complete server didn't have added the ability to change ports. It is an easy fix, similar to the other server protocols like ftp will work. If desired we can easily add that in as well.

**Comment by ChrisTruncer** [comment]
Sure,

If you don’t mind, it might as well be added.

Otherwise this looks great from my perspective.


________________________________

**Comment by ChrisTruncer** [comment]
Just want to check, this good to merge?

**Comment by khr0x40sh** [comment]
The last time we ran it, we believe we fixed all the bugs.

I would think it is.

**Comment by butlerallenj** [comment]
@ChrisTruncer Do you want to replace the current `dns` module with our `dns_complete` module? We can make that change and push another commit to this PR.

**Comment by ChrisTruncer** [comment]
Yeah, might as well replace it since the current module isn’t working. Once replaced, just comment in here and I can get it merged in.

**Comment by khr0x40sh** [comment]
Should be good to go now. Sorry for the delay

**Comment by ChrisTruncer** [comment]
OK, just seeing this is good to go, will merge in

Thanks!

**Comment by ChrisTruncer** [comment]
Thank you all for your help adding this in!

**Pull request merged**
